const PREFIX = 'NEXT_'

export default {
  NEXT_FETCH: `${PREFIX}FETCH`,
	FETCH_REQUEST: `${PREFIX}FETCH_REQUEST`,
	FETCH_SUCCESS: `${PREFIX}FETCH_SUCCESS`,
	FETCH_FAILURE: `${PREFIX}FETCH_FAILURE`
}
